### ISSUE TITLE
missing elements

### ISSUE THREAD

**Issue by zferdana** [CoastalResilienceNetwork/map-tree#1]
original implementation has an odd new font, information icons are missing, zoom to missing, and print icon along top black bar missing

**Comment by zferdana** [comment]
when I use the master branch of the framework the map tree elements are fine; so the missing elements in map tree are only happening when I currently use the develop branch of the framework

**Comment by mmcfarland** [comment]
This is probably due to a misconfigured `map-tree` installation.  Since map-tree refers to the repo but the code itself has references to the `layer_selector` in its path, importantly to the path for the css.  On the `master` branch the layer_selector css is presently embedded in the included map-tree, so it would attach correctly.  I think by using a `name: layer_selector` for your map-tree plugin, this problem will be resolved (and by updating any corresponding `plugins/map-tree` to `plugins/layer_selector`).

**Comment by zferdana** [comment]
Yes! This worked, thanks. But we still have an issue with two map tree/layer selector plugins in a single site. See https://github.com/CoastalResilienceNetwork/california-region/blob/development/plugins.json
